@echo off
cd /d "%~dp0"

set ZIPFILE=%~dp0missing_nvrams.zip
set LISTFILE=%TEMP%\missing_nvrams_list.txt

if exist "%ZIPFILE%" del "%ZIPFILE%"

(
  echo abv105.nv
  echo abv106.nv
  echo abv106r.nv
  echo acd_121.nv
  echo acd_125.nv
  echo acd_130.nv
  echo acd_140.nv
  echo acd_150.nv
  echo acd_150h.nv
  echo acd_152.nv
  echo acd_152h.nv
  echo acd_160.nv
  echo acd_160h.nv
  echo acd_161.nv
  echo acd_161h.nv
  echo acd_163.nv
  echo acd_163h.nv
  echo acd_165.nv
  echo acd_165h.nv
  echo acd_168.nv
  echo acd_168c.nv
  echo acd_168h.nv
  echo acd_168hc.nv
  echo acd_170.nv
  echo acd_170c.nv
  echo afm_10.nv
  echo afm_11.nv
  echo afm_11pfx.nv
  echo afm_11u.nv
  echo afm_f20.nv
  echo afm_f32.nv
  echo agfoot07.nv
  echo agfootbl.nv
  echo agfootbl25l.nv
  echo agsocc07.nv
  echo agsoccer.nv
  echo agsoccer25l.nv
  echo alib.nv
  echo alifp.nv
  echo amazon3a.nv
  echo amazonh.nv
  echo amazonha.nv
  echo andrett4.nv
  echo andromea.nv
  echo andromed.nv
  echo arenaf.nv
  echo arenag.nv
  echo astannie.nv
  echo attack.nv
  echo attila.nv
  echo aust201.nv
  echo aust300.nv
  echo aust301.nv
  echo austinf.nv
  echo austing.nv
  echo austini.nv
  echo avr_101h.nv
  echo avr_106.nv
  echo avr_120h.nv
  echo avs_110.nv
  echo avs_120h.nv
  echo avs_140.nv
  echo avs_140h.nv
  echo avs_170hc.nv
  echo babypaca.nv
  echo babypacn.nv
  echo badgirlf.nv
  echo badgirlg.nv
  echo batmanf1.nv
  echo batmanf2.nv
  echo batmanf3.nv
  echo bay_402.nv
  echo bay_d300.nv
  echo bay_f201.nv
  echo bbb108.nv
  echo bbh_140.nv
  echo bbh_150.nv
  echo bbh_160.nv
  echo bbnny_lu.nv
  echo bcats_.nv
  echo bcats_f1.nv
  echo bcats_g4.nv
  echo bcats_l2.nv
  echo bcats_tcm12.nv
  echo bcats_tcm13.nv
  echo bdk_210.nv
  echo bdk_220.nv
  echo bdk_240.nv
  echo bdk_290.nv
  echo bdk_294c.nv
  echo bdk_300.nv
  echo beachbms.nv
  echo beatclc2.nv
  echo bguns_l7.nv
  echo bguns_lac.nv
  echo bguns_p1.nv
  echo biggameb.nv
  echo biggamec.nv
  echo biggamed.nv
  echo biggamfp.nv
  echo bighousf.nv
  echo bighousg.nv
  echo bk2k_lg1.nv
  echo bk2k_lg3.nv
  echo bk2k_pa7.nv
  echo bk2k_pf1.nv
  echo bk2k_pu1.nv
  echo bk_f4.nv
  echo bk_l3.nv
  echo black10s.nv
  echo blackbl2.nv
  echo blackjcc.nv
  echo blckhole.nv
  echo blkhol7s.nv
  echo blkhole2.nv
  echo blkholea.nv
  echo blkshpsq.nv
  echo blvelvet.nv
  echo bnzai_g3.nv
  echo bnzai_l1.nv
  echo bnzai_pa.nv
  echo bnzai_t3.nv
  echo bonebstf.nv
  echo bonebstg.nv
  echo bop_l2.nv
  echo bop_l3.nv
  echo bop_l4.nv
  echo bop_l5.nv
  echo bop_l6.nv
  echo bountyhg.nv
  echo br_l1.nv
  echo br_l3.nv
  echo br_p17.nv
  echo break.nv
  echo bsb105.nv
  echo bsv100r.nv
  echo bsv102.nv
  echo bsv102r.nv
  echo bsv103.nv
  echo btmn_101.nv
  echo btmn_f13.nv
  echo btmn_g13.nv
  echo bttf_a20.nv
  echo bullsen2.nv
  echo bullsey2.nv
  echo bullseyn.nv
  echo bushidob.nv
  echo camlight.nv
  echo catacofp.nv
  echo cataconb.nv
  echo caveman.nv
  echo cavemana.nv
  echo cc_10.nv
  echo cc_104.nv
  echo cc_12.nv
  echo cc_13k.nv
  echo cerberus.nv
  echo cftbl_l2.nv
  echo cftbl_l3.nv
  echo cftbl_p3.nv
  echo charlies.nv
  echo cheetafp.nv
  echo cheetah1.nv
  echo cheetah2.nv
  echo cheetahb2.nv
  echo chucklck.nv
  echo clash.nv
  echo cleoptra.nv
  echo closeenc.nv
  echo cntforc7.nv
  echo cntforce.nv
  echo coneyis.nv
  echo congo_11.nv
  echo congo_13.nv
  echo corsarfp.nv
  echo corsario.nv
  echo corv_la1.nv
  echo corv_lx1.nv
  echo corv_lx2.nv
  echo corv_px4.nv
  echo countdwn.nv
  echo cp_15.nv
  echo cp_16pfx.nv
  echo cpthook.nv
  echo csi_103.nv
  echo csi_104.nv
  echo csi_200.nv
  echo csi_210.nv
  echo csi_230.nv
  echo csi_240.nv
  echo cue.nv
  echo cv_11.nv
  echo cv_d52.nv
  echo cycln_l1.nv
  echo cycln_l4.nv
  echo cyclope1.nv
  echo dd_l3c.nv
  echo dd_lu1.nv
  echo dd_p06.nv
  echo dd_p6.nv
  echo dd_p7.nv
  echo dh_lf2.nv
  echo diamondf.nv
  echo diamondg.nv
  echo diner_f2.nv
  echo diner_g2.nv
  echo diner_l1.nv
  echo diner_l2.nv
  echo diner_l3.nv
  echo diner_l4fr.nv
  echo diner_p0.nv
  echo dm_h5.nv
  echo dm_h5b.nv
  echo dm_la1.nv
  echo dm_lx3.nv
  echo dm_pa2.nv
  echo dm_px5.nv
  echo drac_l2c.nv
  echo drac_p11.nv
  echo draculc.nv
  echo dragfib2.nv
  echo dragfifp.nv
  echo dragfis14.nv
  echo dragfis3.nv
  echo dragfis3b.nv
  echo dragfisb.nv
  echo dragon.nv
  echo dvlsdre.nv
  echo dvlsdre2.nv
  echo dw_l1.nv
  echo dw_p5.nv
  echo eatpm_3g.nv
  echo eatpm_4g.nv
  echo eatpm_4u.nv
  echo eatpm_f1.nv
  echo eatpm_l1.nv
  echo eatpm_p7.nv
  echo eballch2.nv
  echo eballdlb.nv
  echo eballdlc.nv
  echo eballdp1.nv
  echo eballdp2.nv
  echo eballdp3.nv
  echo eballdp4.nv
  echo eclipse7.nv
  echo eightblo.nv
  echo eldorado.nv
  echo elv100.nv
  echo elv302.nv
  echo elv302f.nv
  echo elv302g.nv
  echo elv302i.nv
  echo elv302l.nv
  echo elv303.nv
  echo elv303f.nv
  echo elv303g.nv
  echo elv303i.nv
  echo elv303l.nv
  echo elv400.nv
  echo elv400f.nv
  echo elv400g.nv
  echo elv400i.nv
  echo elv400l.nv
  echo elvisf.nv
  echo elvisg.nv
  echo elvisi.nv
  echo elvisl.nv
  echo embryonb.nv
  echo embryonc.nv
  echo embryone.nv
  echo esclwrlg.nv
  echo esha_lg1.nv
  echo esha_lg2.nv
  echo esha_pa1.nv
  echo esha_pa4.nv
  echo esha_pr4.nv
  echo excalibg.nv
  echo f14_p3.nv
  echo f14_p4.nv
  echo f14_p5.nv
  echo famlyfun.nv
  echo fathomb.nv
  echo ffv101.nv
  echo ffv103.nv
  echo fg_1200ag.nv
  echo fg_1200ai.nv
  echo fg_1200al.nv
  echo fh_f91.nv
  echo fh_l2.nv
  echo fh_l4.nv
  echo fh_l5.nv
  echo fh_pa1.nv
  echo fire_l2.nv
  echo flashgdp.nv
  echo flashgp2.nv
  echo flight2m.nv
  echo flight2mb.nv
  echo flightfp.nv
  echo forceii.nv
  echo forceii7.nv
  echo freefafp.nv
  echo frpwr_a6.nv
  echo frpwr_a7.nv
  echo frpwr_b6.nv
  echo frpwr_c6.nv
  echo frpwr_d6.nv
  echo frpwr_d7.nv
  echo frpwr_e7.nv
  echo fs_la5.nv
  echo fs_lx2.nv
  echo fs_lx3.nv
  echo fs_lx4.nv
  echo ft_l3.nv
  echo ft_l4.nv
  echo ft_p2.nv
  echo ft_p4.nv
  echo gi_l3.nv
  echo gi_l4.nv
  echo gi_l6.nv
  echo goldbalb.nv
  echo goldbalc.nv
  echo goldcue.nv
  echo gpr301.nv
  echo gpr301f.nv
  echo gpr301g.nv
  echo gpr301i.nv
  echo gpr301l.nv
  echo gpr340.nv
  echo gpr340f.nv
  echo gpr340g.nv
  echo gpr340i.nv
  echo gpr340l.nv
  echo gpr350.nv
  echo gpr350f.nv
  echo gpr350g.nv
  echo gpr350i.nv
  echo gpr350l.nv
  echo gpr352.nv
  echo gpr352f.nv
  echo gpr352g.nv
  echo gpr352i.nv
  echo gpr352l.nv
  echo gpr400.nv
  echo gpr400f.nv
  echo gpr400g.nv
  echo gpr400i.nv
  echo gpr400l.nv
  echo gprix.nv
  echo gprixf.nv
  echo gprixg.nv
  echo gprixi.nv
  echo gprixl.nv
  echo granny.nv
  echo gransl4a.nv
  echo granslaa.nv
  echo granslam.nv
  echo grgar_l2.nv
  echo gs_l3.nv
  echo gs_l4.nv
  echo gs_lg6.nv
  echo gs_lu3.nv
  echo gw_l1.nv
  echo gw_l2.nv
  echo gw_l3.nv
  echo gw_p7.nv
  echo gw_pb.nv
  echo gw_pc.nv
  echo hardbdyg.nv
  echo hh7.nv
  echo hh_1.nv
  echo hirol_fr.nv
  echo hirol_g3.nv
  echo hirol_gr.nv
  echo hirol_it.nv
  echo hirolcas.nv
  echo hirolcat.nv
  echo hook_401p.nv
  echo hs_p4g.nv
  echo hulk.nv
  echo i500_11b.nv
  echo icefever.nv
  echo ij4_210f.nv
  echo ij_h1.nv
  echo ij_l3.nv
  echo ij_l4.nv
  echo ij_l5.nv
  echo ij_l6.nv
  echo ij_lg7.nv
  echo im_140.nv
  echo im_160.nv
  echo im_181.nv
  echo im_182.nv
  echo im_183.nv
  echo im_185.nv
  echo im_186.nv
  echo ironmafp.nv
  echo jack2opn.nv
  echo jamesb.nv
  echo jamesb2.nv
  echo jamesb7.nv
  echo jamesb7b.nv
  echo jb_10b.nv
  echo jm_05r.nv
  echo jm_12b.nv
  echo jokrz_l3.nv
  echo jy_03.nv
  echo jy_11.nv
  echo kpb105.nv
  echo kpv106.nv
  echo krull.nv
  echo lah_107.nv
  echo lah_c106.nv
  echo lah_f104.nv
  echo lah_l104.nv
  echo lah_l108.nv
  echo lazrlord.nv
  echo lightnfp.nv
  echo lotr4.nv
  echo lotr41.nv
  echo lotr5.nv
  echo lotr51.nv
  echo lotr6.nv
  echo lotr7.nv
  echo lotr_f41.nv
  echo lotr_f51.nv
  echo lotr_fr4.nv
  echo lotr_fr5.nv
  echo lotr_fr6.nv
  echo lotr_fr7.nv
  echo lotr_g41.nv
  echo lotr_g51.nv
  echo lotr_gr4.nv
  echo lotr_gr5.nv
  echo lotr_gr6.nv
  echo lotr_gr7.nv
  echo lotr_i41.nv
  echo lotr_i51.nv
  echo lotr_it4.nv
  echo lotr_it5.nv
  echo lotr_it6.nv
  echo lotr_it7.nv
  echo lotr_s51.nv
  echo lotr_sp4.nv
  echo lotr_sp5.nv
  echo lotr_sp6.nv
  echo lotr_sp7.nv
  echo lw3_207.nv
  echo lw3_208p.nv
  echo lw3_300.nv
  echo lw3_301.nv
  echo mars.nv
  echo mars7.nv
  echo mav_404g.nv
  echo meteorc.nv
  echo meteord.nv
  echo meteorfp.nv
  echo mj_l30.nv
  echo mm_05.nv
  echo mm_10u.nv
  echo monop233.nv
  echo monop251.nv
  echo monop301.nv
  echo mousn_l1.nv
  echo mousn_lu.nv
  echo mousn_lx.nv
  echo mt_140.nv
  echo mt_140h.nv
  echo mt_140hb.nv
  echo mt_145.nv
  echo mt_145c.nv
  echo mt_145hb.nv
  echo mtl_160.nv
  echo mtl_160h.nv
  echo mtl_163.nv
  echo mtl_163h.nv
  echo mtl_164.nv
  echo mtl_164c.nv
  echo mtl_164h.nv
  echo mtl_170.nv
  echo mtl_170c.nv
  echo mtl_170hc.nv
  echo mtl_180.nv
  echo mtl_180c.nv
  echo mystcast.nv
  echo myststar.nv
  echo nas301.nv
  echo nas301l.nv
  echo nas340.nv
  echo nas340l.nv
  echo nas350.nv
  echo nas350l.nv
  echo nas352.nv
  echo nas352l.nv
  echo nas400.nv
  echo nas400l.nv
  echo nascarl.nv
  echo nba_801.nv
  echo nbaf_11.nv
  echo nbaf_115.nv
  echo nbaf_11a.nv
  echo nbaf_11s.nv
  echo nbaf_21.nv
  echo nbaf_22.nv
  echo nbaf_23.nv
  echo nbaf_31a.nv
  echo nf_10.nv
  echo ngg_10.nv
  echo ngg_p06.nv
  echo ngndshkm.nv
  echo ninebafp.nv
  echo ninebalb.nv
  echo odin_dlx.nv
  echo orbitofp.nv
  echo orbitora.nv
  echo orbitorb.nv
  echo panther7.nv
  echo panthera.nv
  echo pb_l2.nv
  echo pb_l3.nv
  echo pinpool.nv
  echo play203.nv
  echo play203f.nv
  echo play203g.nv
  echo play203i.nv
  echo play203l.nv
  echo play300.nv
  echo play302.nv
  echo play302f.nv
  echo play302g.nv
  echo play302i.nv
  echo play302l.nv
  echo play303.nv
  echo play303f.nv
  echo play303g.nv
  echo play303i.nv
  echo play303l.nv
  echo play401.nv
  echo play401f.nv
  echo play401g.nv
  echo play401i.nv
  echo play401l.nv
  echo playboyf.nv
  echo playboyg.nv
  echo playboyi.nv
  echo playboyl.nv
  echo pmv112.nv
  echo pmv112r.nv
  echo pnkpnthr.nv
  echo pnkpntr7.nv
  echo polic_l2.nv
  echo polic_l3.nv
  echo polic_lx5.nv
  echo pool_l6.nv
  echo pool_le2.nv
  echo pool_p7.nv
  echo pop_pa3.nv
  echo pot_600gf.nv
  echo potc_600af.nv
  echo potc_600ai.nv
  echo punk.nv
  echo pz_l1.nv
  echo pz_l2.nv
  echo qbquest.nv
  echo quicksfp.nv
  echo rab_103.nv
  echo rab_103it.nv
  echo rab_110be.nv
  echo rackemup.nv
  echo radcl_g1.nv
  echo radcl_p3.nv
  echo raimfire.nv
  echo rct400.nv
  echo rct400f.nv
  echo rct400g.nv
  echo rct400i.nv
  echo rct400l.nv
  echo rct600.nv
  echo rct600f.nv
  echo rct600i.nv
  echo rct600l.nv
  echo rct701.nv
  echo rct701f.nv
  echo rct701g.nv
  echo rct701i.nv
  echo rct701l.nv
  echo rctycnf.nv
  echo rctycng.nv
  echo rctycni.nv
  echo rctycnl.nv
  echo rdkng_l1.nv
  echo rdkng_l2.nv
  echo rdkng_l3.nv
  echo rocky.nv
  echo roldisco.nv
  echo rollr_e1.nv
  echo rollr_ex.nv
  echo rollr_g3.nv
  echo rollr_l3.nv
  echo rollr_p2.nv
  echo rollr_ta2.nv
  echo rollst21.nv
  echo rs_la4.nv
  echo rs_la5.nv
  echo rs_lx2.nv
  echo rs_lx3.nv
  echo rs_lx4.nv
  echo rs_lx5.nv
  echo rsn_110.nv
  echo rsn_110h.nv
  echo sc_14.nv
  echo sc_17.nv
  echo sc_17n.nv
  echo sc_18.nv
  echo sc_18n.nv
  echo sfight2b.nv
  echo shr_130.nv
  echo shrky207.nv
  echo shrky_fr.nv
  echo shrky_gr.nv
  echo shrky_it.nv
  echo shrkysht.nv
  echo simp204.nv
  echo simp204f.nv
  echo simp204i.nv
  echo simp204l.nv
  echo sinbad.nv
  echo sman_260.nv
  echo sman_262.nv
  echo smanve_100.nv
  echo smanve_100c.nv
  echo smb1.nv
  echo smb2.nv
  echo smmanb.nv
  echo solaride.nv
  echo sorbit.nv
  echo speake4a.nv
  echo speakesa.nv
  echo spidermn.nv
  echo splitsfp.nv
  echo sprbrks.nv
  echo sprk_090.nv
  echo sprk_096.nv
  echo ss_01.nv
  echo ss_01b.nv
  echo ss_03.nv
  echo ss_12.nv
  echo ss_14.nv
  echo st_150.nv
  echo st_150h.nv
  echo st_160.nv
  echo st_160h.nv
  echo st_161.nv
  echo st_161c.nv
  echo stargat5.nv
  echo stargzfp.nv
  echo stargzrb.nv
  echo starrac7.nv
  echo starrace.nv
  echo striker.nv
  echo sttng_g7.nv
  echo sttng_l1.nv
  echo sttng_l2.nv
  echo sttng_p4.nv
  echo sttng_p5.nv
  echo sttng_s7.nv
  echo stwr_107s.nv
  echo stwr_e12.nv
  echo stwr_g11.nv
  echo t2_l2.nv
  echo t2_l3.nv
  echo t2_l4.nv
  echo t2_l6.nv
  echo t2_p2f.nv
  echo taf_l1.nv
  echo taf_l2.nv
  echo taf_l3.nv
  echo taf_l4.nv
  echo taf_p2.nv
  echo tafg_la2.nv
  echo tafg_la3.nv
  echo taxi_l3.nv
  echo taxi_lg1.nv
  echo teedoff1.nv
  echo term3_2.nv
  echo term3_3.nv
  echo term3f.nv
  echo term3f_2.nv
  echo term3f_3.nv
  echo term3g.nv
  echo term3g_3.nv
  echo term3i.nv
  echo term3i_2.nv
  echo term3i_3.nv
  echo term3l.nv
  echo term3l_2.nv
  echo term3l_3.nv
  echo tf_170.nv
  echo tftc_104.nv
  echo thegames.nv
  echo thund_p1.nv
  echo timelin7.nv
  echo timeline.nv
  echo tmnt_200.nv
  echo tom_06.nv
  echo tom_10f.nv
  echo tom_12.nv
  echo tomy_h30.nv
  echo torch.nv
  echo totan_04.nv
  echo totan_12.nv
  echo totan_13.nv
  echo totem.nv
  echo touchdn.nv
  echo trek_110.nv
  echo trek_11a.nv
  echo trn_170.nv
  echo trn_17402.nv
  echo trucksp2.nv
  echo trucksp3.nv
  echo ts_la2.nv
  echo ts_la4.nv
  echo ts_la6.nv
  echo ts_lf6.nv
  echo ts_lh6.nv
  echo ts_lm6.nv
  echo ts_lx4.nv
  echo ts_pa1.nv
  echo tsptr_l3fj.nv
  echo tsptr_lx4.nv
  echo tsptr_lx4b.nv
  echo twd_156.nv
  echo twd_156c.nv
  echo twd_156hc.nv
  echo twd_160.nv
  echo twd_160c.nv
  echo twd_160hc.nv
  echo twenty4_130.nv
  echo twenty4_140.nv
  echo twenty4_144.nv
  echo twst_300.nv
  echo twst_404.nv
  echo tz_f86.nv
  echo tz_h7.nv
  echo tz_h8.nv
  echo tz_ifpa.nv
  echo tz_l1.nv
  echo tz_l2.nv
  echo tz_l3.nv
  echo tz_p3.nv
  echo tz_p4.nv
  echo tz_pa1.nv
  echo usafootb.nv
  echo vectorb.nv
  echo viperfp.nv
  echo vlcno_1a.nv
  echo vlcno_1b.nv
  echo vlcno_a7.nv
  echo vlcno_ax.nv
  echo vlcno_b7.nv
  echo wcs_f62.nv
  echo wcs_p2.nv
  echo wcs_p3.nv
  echo wcsoccd2.nv
  echo wd_03r.nv
  echo wd_048r.nv
  echo wd_10f.nv
  echo wd_10g.nv
  echo wd_10r.nv
  echo wd_11.nv
  echo whirl_l2.nv
  echo wildfyrc.nv
  echo wof_500.nv
  echo wof_500f.nv
  echo wof_500g.nv
  echo wof_500i.nv
  echo wof_500l.nv
  echo wpt_140af.nv
  echo wpt_140ai.nv
  echo wpt_140al.nv
  echo wpt_140f.nv
  echo wpt_140g.nv
  echo wpt_140gf.nv
  echo wpt_140i.nv
  echo wpt_140l.nv
  echo wrldtou3.nv
  echo wrldtou4.nv
  echo wrldtour.nv
  echo ww_l2.nv
  echo ww_l3.nv
  echo ww_l4.nv
  echo ww_lh5.nv
  echo ww_p8.nv
  echo wwfr_103f.nv
  echo xfiles304.nv
  echo xmn_150.nv
  echo xmn_151.nv
  echo xmn_151c.nv
  echo xmn_151hc.nv
) > "%LISTFILE%"

powershell -NoProfile -Command "$list = Get-Content '%LISTFILE%'; $found = 0; Add-Type -AssemblyName System.IO.Compression.FileSystem; $zip = [System.IO.Compression.ZipFile]::Open('%ZIPFILE%', 'Create'); foreach ($f in $list) { if (Test-Path $f) { [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile($zip, (Resolve-Path $f), $f) | Out-Null; $found++ } }; $zip.Dispose(); Write-Host ('Done. Added ' + $found + ' files to missing_nvrams.zip')"

del "%LISTFILE%"
pause